### PR TITLE
closing tag search is case-insensitive

### LINKED ISSUE #229: Uppercase Tags Handled Incorrectly
HTML:

``` html
<CUSTOM-TAG></CUSTOM-TAG><div>Hello :)</div>
```

Expected result:

``` html
<custom-tag></custom-tag><div>Hello :)</div>
```

The result which causes hours of debugging of a complex build system:

``` html
<custom-tag><div>Hello :)</div></custom-tag>
```

The same happens with standard tags too.

### PR DESCRIPTION
**Pull request by duncanbeevers**
Fixes #229

### CODE REVIEW

**Comment by duncanbeevers** [comment]
Fixes #227

**Comment by duncanbeevers** [comment]
Fixes #228

**Comment by kangax** [comment]
Thanks @duncanbeevers!

**Comment by AlicanC** [comment]
@duncanbeevers, thanks a lot!

**Pull request merged**
