### PR TITLE
handle line-breaks around custom fragments gracefully

### PR DESCRIPTION
**Pull request by alexlamsl**
@gzzhanghao this is what I have in mind with regards to #716 and #719. Does this address all your cases?

### CODE REVIEW

**Comment by gzzhanghao** [comment]
It works like a charm! Can't wait to merge this :smiley:

**Comment by gzzhanghao** [comment]
The issue in #716 still exists in this branch. I think we should restore all substitutions in the `escapeFragments` method.

**Comment by alexlamsl** [comment]
@gzzhanghao thanks for the review - I'll go fix it up now... :wink:

**Comment by alexlamsl** [comment]
Just tried your example in #716 and it seems to work:

```
> minify(`<script>
... function a() {
.....   b()
.....   <?php if (false): ?>
.....     c()
.....   <?php endif; ?>
..... }
... </script>`, {minifyJS:true})
'<script>function a(){b(),\n<?php if (false): ?>\n,c(),\n<?php endif; ?>\n}</script>'
```

What other options have you specified which produce the incorrect results as you described?

**Comment by gzzhanghao** [comment]
@alexlamsl It becomes `<script>function a(){b(),\n\n}</script>` after running in php runtime. The trailing comma leads to a syntax error :(

Custom fragments are not valid javascript stuff, I think we can't simply treat it as a identifier in javascript.

**Comment by alexlamsl** [comment]
@gzzhanghao now I see what you mean.

Yeah, this one is inherently tricky, and the same issue would arise with `minifyCSS` as well. I guess I'll merge this for now and think about #716 some more, as they are separate issues...

**Pull request merged**
