### PR TITLE
Fix browserify issues #84 #294

### LINKED ISSUE #84: Module "./htmlparser" not found error.
Looks like `global.HTMLParser` doesn't get set properly in some node.js environment. [This line](https://github.com/kangax/html-minifier/blob/a7e68a6f87c327fd0aed2d1261503539d64c9a46/dist/all.js#L393) fails and outputs this error message:

<blockquote>
Error: module "./htmlparser" not found from "./node_modules/rhtml/node_modules/html-minifier/dist/all.js"
</blockquote>

Please set `main` in `package.json` to actual source directory to better support NodeJS. You can distribute client-side library via bower.

### PR DESCRIPTION
**Pull request by jantimon**
This merge request allows using browserify. 

Fixes: #84 and #294

### CODE REVIEW

**Comment by kangax** [comment]
How will this work without parser? https://github.com/kangax/html-minifier/blob/gh-pages/Gruntfile.js#L69

**Comment by jantimon** [comment]
I don't understand your question - I didn't delete anything.

**Comment by kangax** [comment]
I'm saying if we specify main to be src/minifier, how will it work if src/minifier can't work on its own (without parser)

**Comment by jantimon** [comment]
The parser is required: `HTMLParser = require('./htmlparser').HTMLParser;` 

https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js

**Comment by kangax** [comment]
Ahha! Makes sense then, merging.

**Comment by jantimon** [comment]
Cool :)

**Pull request merged**
