### PR TITLE
Allow JSON files and node modules as config files

### LINKED ISSUE #298: minifyJS option - wanting to pass object containing a function from config file to UglifyJS
Hi,
I use the clean multiline string hack and want to inform Uglify to keep comments starting like /*! 
(see http://eli.thegreenplace.net/2013/11/09/javascript-es-5-hack-for-clean-multi-line-strings)

It would seem that parsing of the minifier config file is too strict and is not allowing an object containing a function, hence the following:

something.conf has a line:
"minifyJS": {comments: function (node,comment) { return(comment.charAt(0) === '!'); } },

$ html-minifier --config-file something.conf mysource.html
Error: Cannot read the specified config file

Thanks

### PR DESCRIPTION
**Pull request by fregante**
Fixes #298

Untested because `npm i` is currently hanging for me…

### CODE REVIEW

**Comment by kangax** [comment]
@bfred-it did you have a chance to test it yet?

**Comment by kangax** [comment]
@bfred-it ping

**Comment by fregante** [comment]
I'll try next week, sorry for the delay

**Comment by fregante** [comment]
Okay, I tested it and it works correctly. I also added more explicit error messages, I hope I didn't go overboard.

**Comment by kangax** [comment]
Great, thanks!

**Pull request merged**
