### PR TITLE
Add `removeCustomFragmentsWrap`option

### PR DESCRIPTION
**Pull request by yshterev**
If custom fragments are inside `src` or `href` attribute, the space breaks paths. 

Example:

``` html
<img src="{$assets_dist}img/logo.png" alt="Logo">
```

becomes

``` html
<img src="{$assets_dist} img/logo.png" alt="Logo">
```

### CODE REVIEW

**Comment by alexlamsl** [comment]
I believe this has already been fixed - please check [online version](http://kangax.github.io/html-minifier/)

**Comment by alexlamsl** [comment]
Fun fact - your new test case passes _without_ any changes to `htmlminifier.js`...

**Comment by yshterev** [comment]
Hm.. yes it works from the fork but it does not work when I install from npm. 
Is it possible the npm package is not updated with latest changes ?

I know the test is a little weird :) .. I just wanted to verify my case will work..a legacy smarty project

**Comment by alexlamsl** [comment]
The fix is merged but not published yet - follow #547 for when we do :wink: 

Thanks for reporting and working on it nonetheless. I'll close this for now and add it to our changelog, but if you find anything that doesn't work in the online version, please don't hesitate to help out!

**Comment by yshterev** [comment]
Sure :thumbsup: Thanks for the quick response.

**Pull request closed without merging**
