### PR TITLE
Unified the preserveLineBreak(s) option naming

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Sorry about that. Can it be published to npm?

**Comment by kangax** [comment]
Can't overwrite. Need to tag another version.

**Comment by LaurentGoderre** [comment]
Would it be annoying to have v0.6.8

**Comment by kangax** [comment]
Slightly :) Could you please make a PR with the version change and I'll merge/publish once I get some free time.

**Pull request merged**
