### PR TITLE
fix interaction between htmlmin:ignore & ignoreCustomComments

### PR DESCRIPTION
**Pull request by alexlamsl**
Added tests to cover the breakage.

@XhmikosR sorry for not catching this earlier - please review?

### CODE REVIEW

**Comment by XhmikosR** [comment]
Thanks! I'll try it in a couple of hours and let you know.

**Comment by XhmikosR** [comment]
@alexlamsl: confirmed, it fixes my use case.

**Comment by XhmikosR** [comment]
@alexlamsl: will you cut a new patch release with this fix?

**Comment by alexlamsl** [comment]
@XhmikosR thanks for the testing - I'll make a release later this weekend unless you have more regressions to report...

**Comment by XhmikosR** [comment]
No, I think that's for now. Thanks!

**Pull request merged**
