### PR TITLE
Added isIgnoredComment()

### PR DESCRIPTION
**Pull request by mhulse**
Patch for issue #70.

### CODE REVIEW

**Comment by kangax** [comment]
Looks good. We just need some tests for this.

**Comment by mhulse** [comment]
> Looks good. We just need some tests for this.

I've added 3 tests so far (copied from "removing comments" section, and added the `!` character):

``` js
  test('ignoring comments', function(){
    input = '<!--! test -->';
    equal(minify(input, { removeComments: true }), input);

    input = '<!--! foo --><div>baz</div><!--! bar\n\n moo -->';
    equal(minify(input, { removeComments: true }), input);
    equal(minify(input, { removeComments: false }), input);
  });
```

> Results: ignoring comments (0, 3, 3)

... and, running `$ npm test` 337 of 337 tests passed.

Can you think other tests I should add? Should I account for "ignored" comments within attributes and/or a combination "ignored" comments with "regular" `<!-- this is a regular -->` comments within the same test? I figured attribute comments would be covered under the "removing comments" section as attribute comments don't get stripped anyway.

I have not pushed the above tests to the remote yet ... Kinda wanted to get some feedback before I send an update to my PR. :smile:

Thanks for the help!

**Comment by kangax** [comment]
@mhulse That's pretty good. You can add more combinations, if you wish, but not necessary. Between these and existing tests, I think it covers new functionality pretty well.

**Comment by mhulse** [comment]
Allrighty, I've added 13 tests. Results:

``` bash
$ npm test

> html-minifier@0.5.3 test /Volumes/.../html-minifier
> jshint src/htmlminifier.js src/htmllint.js && cat src/htmlparser.js src/htmlminifier.js src/htmllint.js > dist/all.js && node test.js


Testing /Volumes/.../html-minifier/src/htmlminifier.js ... done
Summary:
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┓
┃ File                                               ┃ Failed   ┃ Passed   ┃ Total    ┃ Runtime  ┃
┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━━━╋━━━━━━━━━━┫
┃ ...mhulse/github/html-minifier/src/htmlminifier.js ┃ 0        ┃ 347      ┃ 347      ┃ 78       ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━┻━━━━━━━━━━┻━━━━━━━━━━┻━━━━━━━━━━┛

Global summary:
┏━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Files      ┃ Tests      ┃ Assertions ┃ Failed     ┃ Passed     ┃ Runtime    ┃
┣━━━━━━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━┫
┃ 1          ┃ 43         ┃ 347        ┃ 0          ┃ 347        ┃ 78         ┃
┗━━━━━━━━━━━━┻━━━━━━━━━━━━┻━━━━━━━━━━━━┻━━━━━━━━━━━━┻━━━━━━━━━━━━┻━━━━━━━━━━━━┛
```

... and the results from `/html-minifier/tests`:

> Tests completed in 114 milliseconds.
> 338 tests of 338 passed, 0 failed.

Let me know if you'd like me to add more tests and/or do anything else to help out. :+1: 

Thanks again!!!! Excellent work on all of this code, it's a pretty cool utility. :octocat:

**Pull request merged**
