### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by XhmikosR**
Now Travis should work hopefully.

### CODE REVIEW

**Comment by XhmikosR** [comment]
https://travis-ci.org/kangax/html-minifier/builds/17493755

**Comment by kangax** [comment]
Awesome, thanks!

**Comment by XhmikosR** [comment]
No problem, every day we learn something new :)

BTW, do you really want to support Node.js v0.6? If not you should remove it from travis and bump `engines` in package.json.

**Comment by kangax** [comment]
Should be all good now

**Pull request merged**
