### PR TITLE
Fixed nested quotes not being properly escaped

### PR DESCRIPTION
**Pull request by LaurentGoderre**
This addresses the immediate problem from #264

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Can we merge this to fix the immediate problem with JSON in attributes?

**Comment by XhmikosR** [comment]
@LaurentGoderre: if you add tests which pass, I'd be glad to have a look and merge this.

**Comment by LaurentGoderre** [comment]
There was already a test but adding a more robust one identified a problem with my logic so I updated both

**Comment by XhmikosR** [comment]
@kangax: any objections in merging this?

**Comment by kangax** [comment]
I am not 100% sure that this is the best course of action but it's better than what we currently have and I don't have time to look into it more so... Yeah, I'm ok with merging :)

**Comment by XhmikosR** [comment]
OK, I guess we'll know if we break something in the process. :P

PS. @kangax Maybe you should release a v0.6.9? https://github.com/kangax/html-minifier/compare/v0.6.8...gh-pages?w=false

**Comment by XhmikosR** [comment]
@LaurentGoderre: this seems to break some browser tests with FF 33 at least  http://kangax.github.io/html-minifier/tests/

**Comment by LaurentGoderre** [comment]
How do I reproduce this locally? Also, this did not change the logic that is failing

**Comment by LaurentGoderre** [comment]
@XhmikosR can we try merging #276 first. They could be a problem if the source and test do not match the dist folder

**Comment by XhmikosR** [comment]
@LaurentGoderre: locally, you need Ruby and Jekyll as this is what GitHub pages use. But anyway I solved this by running `grunt`.

**Pull request merged**
