### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by XhmikosR**
@kangax:Let me know if you want me to change anything and I will rebase the branch.

### CODE REVIEW

**Comment by XhmikosR** [comment]
http://xhmikosr.github.io/html-minifier/
http://xhmikosr.github.io/html-minifier/tests/

**Comment by kangax** [comment]
@XhmikosR Everything looks good, thanks! The only question — why the removal of some stuff from .jshintrc? Are these the declarations that are being dropped in 3.0?

**Comment by XhmikosR** [comment]
@kangax: I basically removed most options that are on by default. And sorted the remaining entries by name.

BTW, Travis doesn't seem to show for the PR, would be nice to enable it.

**Comment by XhmikosR** [comment]
Another thing, what do you think about moving the web related files to a separate folder? Like "web"? We can make Jekyll use that folder for page generation and the source tree should be cleaner.

Edit: Actually this doesn't work because then the dist directory isn't copied in the output dir.

**Comment by kangax** [comment]
@XhmikosR not sure what's up with Travis; I just enabled it in the profile (had .travis.yml in repo but forgot to enable it on travis side) but it's not appearing yet. Maybe needs more time or maybe something else is off.

**Comment by XhmikosR** [comment]
Maybe it's because the main branch is gh-pages?

**Comment by kangax** [comment]
@XhmikosR maybe... removed master branch; should have done it a while ago : )

**Pull request merged**
