### PR TITLE
Downgrade qunit so that node.js 0.8 works again.

### PR DESCRIPTION
**Pull request by XhmikosR**
More and more issues arise from supporting node.js 0.8...

### CODE REVIEW

**Comment by kangax** [comment]
: /

**Comment by XhmikosR** [comment]
BTW, maybe you could make a new npm release? There aren't any important changes so far, but it shouldn't hurt either :)

**Comment by kangax** [comment]
Sure. Pushed, published.

**Comment by XhmikosR** [comment]
Thanks!

**Comment by kangax** [comment]
Btw, I just created 0.6.0 milestone and added some issues in there that I'd
like to do next --
https://github.com/kangax/html-minifier/issues?milestone=1&page=1&state=open

I'm pretty swamped with work at the moment, and there's also Fabric issues
piling up. I'll try to get to some of these in a near future. Shooting for
1-2 month to finish and push 0.6.0.

**Comment by XhmikosR** [comment]
Sounds good! I guess you can update the deps in that branch and drop node.js 0.8 support since it's becoming a problem more every day...

**Comment by kangax** [comment]
Yeah, we should probably drop it together with 0.6.0 release.

**Comment by XhmikosR** [comment]
BTW, personally apart from the ability to minify inline javascript, I miss the opportunity to cleanly ignore specific code. I use `<!--googleoff: all-->` etc and I only need to keep that from the comments but it's so much trouble to work around this :/

**Comment by kangax** [comment]
Ok, added.

**Pull request merged**
