### PR TITLE
Ooops, CLI does not work when html-minifier is installed with npm install html-minifier -g

### PR DESCRIPTION
**Pull request by tssajo**
Today I installed html-minifier on a Mac with `npm install html-minifier -g` command and noticed that the CLI interface did not get installed at all... :(

Here is the fix: we must include `cli.js` in the `"files"` section of `package.json` file. It's kind of important.

While at it, I did some other improvements in my cli.js code, fixed a small issue in README.md file, etc.

Can you please merge these changes?

Thanks!!

### CODE REVIEW

**Comment by kangax** [comment]
Thanks!

**Comment by tssajo** [comment]
Thanks for merging.

However, when trying to install html-minifier globally with the command:
`npm install html-minifier -g`
the files `cli.js` and `sample-cli-config-file.conf` still not get installed...

I cleaned my npm cache with `npm cache clear` to no avail.

Originally how did you publish html-minifier from github.com to npmjs.org at the first place?
Can you somehow "tell" npmjs.org that new files were added to the git repo?
Or is it all automatic and a version bump is required?
Sorry, but I don't know how publishing packages to npm works ... Maybe you do?

**Comment by kangax** [comment]
I just bumped version to 0.6.1 and published it on NPM. Can you please try
again?

**Comment by tssajo** [comment]
Yes, it works now! Thanks!!

**Comment by tssajo** [comment]
You might want to add a release tag for v0.6.1
to show up on the page https://github.com/kangax/html-minifier/releases

**Comment by kangax** [comment]
Good point, pushed. Thanks.

**Pull request merged**
