### PR TITLE
minify Content-Security-Policy

### LINKED ISSUE #947: Please minify Content Security Policy
Current result:

image

### PR DESCRIPTION
**Pull request by alexlamsl**
fixes #947
closes #975

### CODE REVIEW

**Comment by alexlamsl** [comment]
@kangax sorry to bother again, but looks like after migration to travis-ci.com PR build jobs aren't working anymore (was working for .org, e.g. #1005)

I don't know which is easier/faster:
- adding PR to webhook settings
- removing Travis CI from Branch Protection requirements

But whichever way that allows me to merge any PRs would be greatly appreciated.

**Comment by alexlamsl** [comment]
@kangax friendly ping since I can't merge any PRs until this is resolved...

**Comment by kangax** [comment]
@alexlamsl sorry, I was away. Any ideas on how I can fix this?

**Comment by alexlamsl** [comment]
Sorry for nagging - so what happens is that PR-triggered jobs seem to work for `travis-ci.org` but not `travis-ci.com`, even though branch builds are working fine.

So while it could be some settings not enabled on the Travis CI side, but failing to narrow that down just remove Travis CI from the branch protection criteria for now.

**Comment by kangax** [comment]
@alexlamsl what about now?

**Comment by alexlamsl** [comment]
@kangax the merge button now works, thanks!

**Pull request merged**
