### PR TITLE
remove additionally empty attributes

### PR DESCRIPTION
**Pull request by sxend**
Specify the tag name and attribute name as a comma-separated list so that it can be deleted additionally.
(and I'm sorry, my English is not good)

### CODE REVIEW

**Review by alexlamsl — CHANGES_REQUESTED** [review]
I'd consider specifying `Function(attrName, tag)` to `removeEmptyAttributes` which returns a boolean instead of introducing a new option and special string format.

**Comment by sxend** [comment]
Thank you for review.

> Function(attrName, tag) to removeEmptyAttributes

OK. I will fix that way.

**Comment by alexlamsl** [comment]
Looks good - waiting for Travis to complete before merging. Thanks for the work.

**Review by alexlamsl — APPROVED** [review]

**Comment by alexlamsl** [comment]
Let me close-then-open this PR to give Travis a little kick... :sweat_smile:

**Comment by alexlamsl** [comment]
Not sure what's happening over at [Travis](https://travis-ci.org/kangax/html-minifier/pull_requests) - I'll come back later to sort this out.

**Comment by sxend** [comment]
Sorry, committer and author were wrong, so I fixed it and push it again.
When pass CI, Please merge at your favorite timing. :bowing_man:

**Comment by alexlamsl** [comment]
Read the latest changes, still looks good. And thanks for squashing the commits.

**Pull request merged**
