### PR TITLE
Enable JSHint's `quotmark` rule.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by kangax** [comment]
Good stuff @XhmikosR, thanks! We should update to JSCS sometime in the future, since JSHint will be dropping these rules. I started using it on Fabric.js just few days ago — https://github.com/kangax/fabric.js/blob/master/.jscs.json

**Comment by XhmikosR** [comment]
Yeah I too looked into JSCS for Bootstrap but its indentation warnings seemed weird so I didn't spend a lot of time on it. But I will look into getting JSCS to work in the near future.

**Comment by kangax** [comment]
So far it's been pretty flexible, and consider that Fabric's codebase is relatively large (~11,5K LOC).

The only issues I found were https://github.com/mdevils/node-jscs/issues/244, https://github.com/mdevils/node-jscs/issues/247, and https://github.com/mdevils/node-jscs/issues/20#issuecomment-35211776

**Comment by kangax** [comment]
I'll be plugging JSCS validation in Fabric's travis build once those are resolved.

**Comment by XhmikosR** [comment]
That's good news! I also switched to JSCS for the indentation check in Bootstrap but I'm not sure I like its approach. I will push the changes in a separate branch in bootstrap later.

**Comment by XhmikosR** [comment]
Apparently my issue is already reported [here](https://github.com/mdevils/node-jscs/issues/247).

**Pull request merged**
