### PR TITLE
Update relateurl asset

### PR DESCRIPTION
**Pull request by stevenvachon**
Latest version (0.2.6):
- Removes trailing slashes on root URLs ([info](https://github.com/stevenvachon/relateurl#optionsremoveroottrailingslash))
- Minor speed enhancements

### CODE REVIEW

**Comment by XhmikosR** [comment]
How was this file generated?

**Comment by duncanbeevers** [comment]
@XhmikosR releateurl is Steven's own project. https://github.com/stevenvachon/relateurl

It looks like it's generated by browserify.
https://github.com/stevenvachon/relateurl/blob/master/package.json#L35

**Comment by XhmikosR** [comment]
OK, I'm asking for the sake of completeness, because every asset should be able to be generated by everyone without magic :D

**Comment by XhmikosR** [comment]
On a side note, I've been meaning to add a grunt task to generate the assets from the local node_modules or copy them if available. Maybe someone else has more time to do this faster.

**Comment by stevenvachon** [comment]
Thanks for merging.

**Pull request merged**
