### PR TITLE
fix crash in removeOptionalTags

### PR DESCRIPTION
**Pull request by alexlamsl**
also implement the optional start tag rules for empty element cases

### CODE REVIEW

**Comment by alexlamsl** [comment]
@XhmikosR @kangax fixes for #503 is going to conflict with this, so if you can review and merge this first before I open another PR that would be great.

**Comment by XhmikosR** [comment]
I'd still squash those 2 last patches, but otherwise it's much better than the previous PR :)

**Comment by alexlamsl** [comment]
@XhmikosR squashed :pray:

**Comment by alexlamsl** [comment]
rebased (`dist/htmlminifier.min.js` is always in the way...)

**Pull request merged**
