### PR TITLE
Added option to preserve a single line break on collapse

### PR DESCRIPTION
**Pull request by LaurentGoderre**
This improves legibility of the HTML without affecting the compression

### CODE REVIEW

**Comment by kangax** [comment]
Can you please add a test case

**Comment by LaurentGoderre** [comment]
Sure!

**Comment by LaurentGoderre** [comment]
There you go!

**Comment by duncanbeevers** [comment]
@LaurentGoderre Your needs mentioned in [wet-boew#5818](https://github.com/wet-boew/wet-boew/issues/5818) might be served by simply using the `maxLineLength` option recently-added to html-minifier.

As it stands, this PR slightly increases the size of the generated output after gzipping by increasing the total entropy of the input corpus.

You can see the difference in compressed output size by running

```
node benchmark.js
```

Before applying this PR, the html-minifier corpus is agressively gzipped down to 8821 bytes while afterwards it compresses to 8828 bytes.

This is admittedly a pretty negligible difference, but if the `maxLineLength` functionality already incorporated in the project meets your needs, I'd like to avoid taking any hit to the baseline compression performance.

**Comment by LaurentGoderre** [comment]
I admit that I did not think about that. The maxLineLength will not help us but I,m wondering if we are not pursing something unrealistic

**Comment by LaurentGoderre** [comment]
@duncanbeevers @kangax would you be opened to adding this as an option?

**Comment by duncanbeevers** [comment]
I am definitely _not_ against adding it as an option.

Can you explain what problem this pull request alleviates?

**Comment by LaurentGoderre** [comment]
It's a request we have from our <del>user</del> implementers. They want the compression but want to keep some form of readability. We currently use an html minifier that does this but it's Java based and it's soooo slow. This especially helps when dealing with autogenerated output (ex: Jekyll)

**Comment by kangax** [comment]
So it's similar to https://github.com/kangax/html-minifier/issues/129 then?

**Comment by LaurentGoderre** [comment]
Quite similar but this also gets rid of whitespace before and after the line breaks. I'm wondering if this would meet their needs

**Comment by kangax** [comment]
@LaurentGoderre I'm happy to merge this in, but couple things first:
1. Let's rename `preserveLineBreak` to `preserveLineBreaks`. I think it sounds more natural and is consistent with our other options (`removeRedundantAttributes`, `removeAttributeQuotes`, etc.)
2. Let's add a bit more complex test (more markup, e.g. the one from #129), just to be sure everything works as expected.
3. I'm wondering how this affects performance, but considering this is opt-in, I suppose we don't have to worry about it for now (except that `.replace(lineBreakStamp, '\n');` happens all the time now, right? not just when option is `true`?)

**Comment by LaurentGoderre** [comment]
Regarding #3, would you rather it be:

``` js
if (options.preserveLineBreaks) {
  str = str
    .replace(lineBreakBefore, lineBreakStamp)
    .replace(lineBreakAfter, lineBreakStamp);
    .replace(/[\t\n\r]+/g, ' ').replace(/[ ]+/g, ' ')
    .replace(lineBreakStamp, '\n');
} else {
      // strip non space whitespace then compress spaces to one
      return str.replace(/[\t\n\r]+/g, ' ').replace(/[ ]+/g, ' ')
}
```

**Comment by LaurentGoderre** [comment]
Ok, #1 and #2 are done. How do you want to deal with #3? (Note that the logic changed a bit)

**Comment by kangax** [comment]
I think it's good now. Thanks again!

**Comment by LaurentGoderre** [comment]
Can you let me know when you publish to npm?

**Comment by kangax** [comment]
Published!

**Comment by LaurentGoderre** [comment]
Btw, what do we do about the `preserveLineBreak` vs `preserveLineBreaks`?

**Comment by kangax** [comment]
Wait, did we fix it or not?

**Comment by LaurentGoderre** [comment]
I thought I did but I probably screwed up my rebase....sorry about that

**Comment by niftylettuce** [comment]
Line breaks don't seem to be preserved either way - they don't get stripped if this is `false` or `true`.  Not sure what to do here, my code still looks like this output after passing through `html-minifier`:

``` html
<p>Foo</p>


A whole bunch of unwanted 

Line

Breaks
</p>
```

**Pull request merged**
