### PR TITLE
html-minifier: Replaced PhantomJS Dependency

### PR DESCRIPTION
**Pull request by pruthvireddypuresoftware**
PhantomJS is an unmaintained project, replaced Phantomjs with puppeteer support.
Added the necessary files to provide puppeteer support.

Take reference https://github.com/kangax/html-minifier/pull/971.

### CODE REVIEW

**Comment by pruthvireddypuresoftware** [comment]
Hi @alexlamsl @kangax 

Replaced phantomjs with puppeteer as mentioned in https://github.com/kangax/html-minifier/pull/971#issuecomment-478681104

Please have a look at this PR and provide feedback if any issues.

**Comment by pruthvireddypuresoftware** [comment]
@alexlamsl @kangax ,
As mentioned currently phantomjs is unmaintained and puppeteer support has been added. Please review the changes and provide feedback if any issues.

**Comment by rhenwood-arm** [comment]
@alexlamsl @kangax I would like to see PhantomJS replaced as it is not only unmaintained, but it is not available on AArch64. Do you have any feedback on this PR?

**Comment by ossdev07** [comment]
Hi @alexlamsl @kangax

Please have a look at this PR and provide feedback if any issues.

**Comment by pruthvireddypuresoftware** [comment]
Hi @alexlamsl @kangax

Please have a look at this PR and provide feedback if any issues.

**Comment by pruthvireddypuresoftware** [comment]
@alexlamsl @kangax ,

Phantomjs has been replaced with puppeteer as suggested. Please review this PR and provide feedback if any issues.

**Comment by yumin-chen** [comment]
I don't know if this repository still has an active maintainer any more :( Both of them have been unresponsive from this repo for a long time now.

**Comment by XhmikosR** [comment]
@pruthvireddypuresoftware can you please rebase this branch?

**Pull request closed without merging**
