### PR TITLE
Make benchmark.js cross-platform.

### LINKED ISSUE #300: benchmark.js not working on Windows?
I'm getting this

```
C:\Users\xmr\Desktop\html-minifier>node -v && npm -v
v0.10.33
1.4.28

C:\Users\xmr\Desktop\html-minifier>node benchmark.js

Processing... html-minifier

C:\Users\xmr\Desktop\html-minifier\benchmark.js:80
            var minifiedSize = stats.size;
                                    ^
TypeError: Cannot read property 'size' of undefined
    at C:\Users\xmr\Desktop\html-minifier\benchmark.js:80:37
    at Object.oncomplete (fs.js:107:15)
```

Maybe it's due to gzip not available on Windows?
/CC @kangax

### PR DESCRIPTION
**Pull request by XhmikosR**
Also, check for failures in all places.

This is how it looks now on Windows:

```
┌────────────────────┬─────────────────────────┬─────────────────────────┬────────────────────┬────────────────────┐
│ File               │ Before                  │ After                   │ Savings            │ Time               │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ html-minifier      │ 49978 (48.81KB)         │ 38611 (37.71KB)         │ 22.74% (11.10KB)   │ 204ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 219ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ abc                │ 93187 (91.00KB)         │ 78041 (76.21KB)         │ 16.25% (14.79KB)   │ 328ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 328ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ newyorktimes       │ 134565 (131.41KB)       │ 113790 (111.12KB)       │ 15.44% (20.29KB)   │ 328ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 328ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ google             │ 136320 (133.13KB)       │ 129327 (126.30KB)       │ 5.13% (6.83KB)     │ 828ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 843ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ msn                │ 160454 (156.69KB)       │ 136471 (133.27KB)       │ 14.95% (23.42KB)   │ 594ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 610ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ es6-table          │ 120768 (117.94KB)       │ 81968 (80.05KB)         │ 32.13% (37.89KB)   │ 375ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 375ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ amazon             │ 251828 (245.93KB)       │ 211598 (206.64KB)       │ 15.98% (39.29KB)   │ 797ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 797ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ stackoverflow      │ 205280 (200.47KB)       │ 163577 (159.74KB)       │ 20.32% (40.73KB)   │ 406ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 406ms              │
├────────────────────┼─────────────────────────┼─────────────────────────┼────────────────────┼────────────────────┤
│ wikipedia          │ 411051 (401.42KB)       │ 390036 (380.89KB)       │ 5.11% (20.52KB)    │ 453ms              │
│ + gzipped          │ 0 (0.00KB)              │ 0 (0.00KB)              │ NaN% (0.00KB)      │ 453ms              │
└────────────────────┴─────────────────────────┴─────────────────────────┴────────────────────┴────────────────────┘
```

Fixes #300 

/CC @kangax @duncanbeevers

### CODE REVIEW

**Comment by XhmikosR** [comment]
I added a small patch to have the filenames sorted alphabetically. If anyone has a simpler/better solution let me know.

**Comment by XhmikosR** [comment]
Hmm, perhaps I should just use `sort()` and thus not relying on manually sorting the array.

**Comment by duncanbeevers** [comment]
I actually preferred the original sorting where the entries were manually sorted by initial corpus size, but again, I have no strong feelings about this.

**Comment by XhmikosR** [comment]
Well, the previous order wasn't right either. I always feel that alphabetical order makes more sense.

Anyway, /CC @kangax for feedback.

**Comment by kangax** [comment]
What about gzip? Doesn't seem to work based on "screenshot"? :)

**Comment by XhmikosR** [comment]
@kangax: Windows doesn't have gzip :/

**Comment by kangax** [comment]
Other than that, LGTM, thanks @XhmikosR!

**Comment by XhmikosR** [comment]
@kangax: are you aware if how to use the cli-table's colors? I'd like to give that a go and see how it works compared to chalk, since I'm a fan of minimal dependencies.

**Comment by kangax** [comment]
@XhmikosR Not really, sorry. I might have used it before but can't recall at the moment.

**Comment by XhmikosR** [comment]
OK, I'll go with chalk for the time being since it is better than what we had previously, anyway.

**Pull request merged**
