### PR TITLE
upgrade devDependencies

### PR DESCRIPTION
**Pull request by alexlamsl**
grunt-contrib-uglify 2.0.0

### CODE REVIEW

**Comment by XhmikosR** [comment]
Note that screwIE8 is enabled by default in v2.0.0. So if you care about IE8 you need to set it to false.

**Comment by alexlamsl** [comment]
Thanks for the reminder - I don't think this codebase has IE8 compatibility, but I'll try and double check with a WinXP VM later this evening.

**Comment by XhmikosR** [comment]
There's nothing to check :p

If you want IE < 9 compatibility just set the option to false.

**Comment by alexlamsl** [comment]
My point was if the pre-minified code already using features not supported by IE8, than `screwIE8` or not is a bit moot...

**Comment by XhmikosR** [comment]
Yup, it already fails on IE8 so I guess just ignore it.

```
SCRIPT438: Object doesn't support property or method 'keys' 
htmlminifier.min.js, line 7 character 2382
SCRIPT5007: The value of the property 'require' is null or undefined, not a Function object 
master.js, line 4 character 3
```

**Pull request merged**
