### PR TITLE
fixes for removeOptionalTags & ignoreCustomFragments

### PR DESCRIPTION
**Pull request by alexlamsl**

### CODE REVIEW

**Comment by alexlamsl** [comment]
So the trouble is with [these lines](https://github.com/kangax/html-minifier/blob/gh-pages/src/htmlminifier.js#L1043-L1053), when both `removeStartTag()` and `removeEndTag()` are triggered.

While fixing #500 I have also noticed the empty content cases for optional start tags are missing, so added those as well.

**Comment by alexlamsl** [comment]
@kangax I know it's been around forever, but should we be unconditionally trim whitespace of input to `minify()` before we even start to parse it, or do you think it should depend on `collapseWhitespace`?

**Comment by alexlamsl** [comment]
@kangax btw, it's been bugging me that `grunt test` runs 9 more tests than the [online version](http://kangax.github.io/html-minifier/tests/), until I realise the existence of `lint-tests.html` :sweat_smile:

**Comment by XhmikosR** [comment]
@alexlamsl: you shouldn't mix unrelated commits. You should merge the unrelated patches to master.

**Comment by kangax** [comment]
@XhmikosR @alexlamsl I agree that large-ish PR's are usually harder to land, since I tend to postpone reviewing them (when I don't have much time to look through all of it and understand; I just keep moving it for later). Small ones are definitely easier to understand and merge so if at all possible, unrelated changes are best extracted. And, as always, thanks for all the continuous help, folks!

**Comment by alexlamsl** [comment]
Wasn't certain about the process - will do for future maintenance commits that are trivial...

Speaking of trivial commits, shall we land #498 before it gets really stale?

**Comment by alexlamsl** [comment]
Thanks a lot for the reviews so far - I know how hard it can be even for me to read my own code sometimes!

**Comment by XhmikosR** [comment]
@alexlamsl: so just rebase and move the following to a new branch and merge them separately

https://github.com/alexlamsl/html-minifier/commit/49a4fa88ce1900a014bf9bc5d9cba730c5bd5281
https://github.com/alexlamsl/html-minifier/commit/0daf5b4adec7dbf70efb21a4411559248ff7539a
https://github.com/alexlamsl/html-minifier/commit/ceefa9ab822df9485d89cdb7695a429841120877
https://github.com/alexlamsl/html-minifier/commit/247d623777dd8b80381acd518ff22321fa365318

Then see if you can squash some of the remaining patches when it makes sense.

**Comment by alexlamsl** [comment]
Let's see what I can do with git here... :sweat_smile:

**Comment by alexlamsl** [comment]
Closing for new PR(s)

**Pull request closed without merging**
