### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by alexlamsl**
- commander 2.19.0
- grunt-contrib-uglify 4.0.1
- gruntify-eslint 5.0.0
- uglify-js 3.5.1

### CODE REVIEW

**Comment by alexlamsl** [comment]
@kangax even the local branch stops triggering Travis CI builds now.

**Comment by alexlamsl** [comment]
Okay according to https://travis-ci.org/kangax/html-minifier

> **This is not an active repository**
>
> You don't have sufficient rights to enable this repo on Travis.
> Please contact the admin to enable it or to receive admin rights yourself.

So I guess you can reactivate it by visiting the page above :wink:

**Comment by kangax** [comment]
Try now

**Comment by XhmikosR** [comment]
We should probably switch to a semver operators later.

**Comment by XhmikosR** [comment]
Also @kangax while at it, can you enable branch protection for master? And make sure you enable hooks to pass, include admins and branches be up to date.

**Comment by kangax** [comment]
@XhmikosR should be good now

**Comment by alexlamsl** [comment]
> We should probably switch to a semver operators later.

I've just search the term on Google — do you mean `~2.0.0` instead of `2.0.x`?

I can update them all in this PR if you prefer.

**Comment by alexlamsl** [comment]
> Try now

I get the CI status reporting back from GitHub now:

> continuous-integration/travis-ci Expected — Waiting for status to be reported

But still no action on the Travis CI front.

**Comment by alexlamsl** [comment]
Tried a brand new commit - still, no 🎲

**Comment by kangax** [comment]
I'm not sure what's going on... I would ideally also like to move to CircleCI. Find it better all around. Will try to find some time for this soon.

**Comment by alexlamsl** [comment]
Okay thanks - in the mean time, should we just remove it since it is blocking any Pull Requests from merging at all?

**Comment by kangax** [comment]
Sure, removed.

**Comment by XhmikosR** [comment]
I wouldn't remove it guys, especially when it seems it's misconfigured hence why it errors out :P

Please add it back, @kangax, but leave it out of the branch protection requirements until I sort it out.

**Comment by XhmikosR** [comment]
@kangax  please see my comment above. We still need CI no matter what.

**Comment by kangax** [comment]
I can't figure out how to migrate this damn thing from what seems to be an old travis system. Spent an hour yesterday fiddling with it with no success. It keeps redirecting me to github settings where i can see that travis is installed but then on travis it says the repo is not active because it's using an old system (even after i disable it in the old system — travis-ci.org rather than travis-ci.com).

**Comment by kangax** [comment]
Just noticed in the docs:

> To have any public repository migrated over, it must be first activated on travis-ci.com using GitHub Apps. 

I've already done this

> Send us an email to support@travis-ci.com with the subject “Open Source Migration Beta Testing” 

🤦🏻

**Comment by XhmikosR** [comment]
I wouldn't bother with migrating. Just enable it in travis-ci.org.

And make sure branches are up to date is enabled. I will have a look at fixing Travis later, but we need it ASAP.

**Comment by alexlamsl** [comment]
@kangax just curious, is there a reason why we want to be on .com not .org? I ask just in case I need to do the same migration for `uglify-js` 😅

**Comment by kangax** [comment]
@alexlamsl looks like it's just their new platform — https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com 

I think it's best to migrate sooner rather than later since they might deprecate the old one at some point.

I sent them an email btw, and they already responded and enabled html-minifier on the new .com; I enabled it there so I'm guessing that concludes the transition 🤷‍♂️

**Comment by alexlamsl** [comment]
Thanks for the trouble 👍

**Comment by XhmikosR** [comment]
I did the migration myself for a few projects, but not all of them could be migrated at the time, so I just left it.

I believe they will do the migration themselves because the number of projects on org is pretty big. :)

**Pull request merged**
