### PR TITLE
'caseSensitive' option now applies to tags as well as attributes

### PR DESCRIPTION
**Pull request by JakobJingleheimer**
Addresses #198

### CODE REVIEW

**Comment by kangax** [comment]
Great, thanks!

**Comment by JakobJingleheimer** [comment]
How does the `/dist` directory get updated?

**Comment by kangax** [comment]
As part of `grunt` (or only concat task)

**Comment by JakobJingleheimer** [comment]
Oh whoops. Should i run that and re-submit? Also, any chance this could get tagged for release?

**Comment by kangax** [comment]
Yes, please resubmit with already bumped version. I'll publish.

**Pull request merged**
